words = [
    "spam",
    "money",
    "offer",
    "click here",
    "subscribe",
    "buy now",
    "free",
    "winner",
    "urgent",
    "limited time",
    "special offer",
    "win",
    "act now",
    "risk-free",
    "guarantee",
    "no obligation",
    "exclusive deal",
    "instant access",
    "cash bonus",
    "double your income",
    "work from home",
    "make money fast",
    "earn extra cash",
    "get paid",
    "financial freedom",
    "passive income",
    "residual income",
    "online business",
    "internet marketing",
    "affiliate marketing",
    "network marketing",
    "multi-level marketing",
    "mlm",
    "pyramid scheme",
    "scam",
    "fraud",
    "deceptive",
    "misleading",
    "false advertising",
    "bait and switch",
    "high-pressure sales tactics",
    "hard sell",
    "pushy sales pitch",
    "unsolicited",
    "spam email",
    "junk mail",
    "phishing",
    "malware",
    "virus",
    "trojan",
    "spyware",
    "adware",
    "ransomware",
    "hacker",
    "cyber attack",
    "data breach",
    "identity theft",
    "credit card fraud",
    "financial scam",
    "investment scam",
    "get-rich-quick scheme",
    "fake lottery",
    "prize draw",
    "sweepstakes",
    "charity scam",
    "romance scam",
    "online dating scam",
    "job scam",
    "work-at-home scam",
    "travel scam",
    "timeshare scam",
    "real estate scam",
    "auto repair scam",
    "home improvement scam",
    "contractor scam",
    "moving scam",
    "storage scam",
    "debt relief scam",
    "credit repair scam",
    "tax scam",
    "IRS scam",
    "government grant scam",
    "student loan scam",
    "loan modification scam",
    "mortgage scam",
    "foreclosure scam",
    "utility scam",
    "phone scam",
    "robocall",
    "telemarketing scam",
    "door-to-door scam",
    "in-person scam",
    "fake check scam",
    "overpayment scam",
    "refund scam",
    "warranty scam",
    "extended warranty scam",
    "service contract scam",
    "insurance scam",
    "health insurance scam",
    "medical billing scam",
    "prescription drug scam",
    "healthcare fraud",
    "medicare fraud",
    "medicaid fraud",
    "pharmacy scam",
    "vaccine scam",
    "covid-19 scam",
    "coronavirus scam",
    "pandemic scam",
    "fake cure",
    "miracle cure",
    "alternative medicine scam",
    "diet scam",
    "weight loss scam",
    "fitness scam",
    "supplement scam",
    "beauty scam",
    "anti-aging scam",
    "skincare scam",
    "hair growth scam",
    "cosmetic surgery scam",
    "plastic surgery scam",
    "dental scam",
    "vision care scam",
    "hearing aid scam",
    "pet care scam",
    "animal health scam",
    "veterinary scam",
    "pet insurance scam",
    "pet adoption scam",
    "animal rescue scam",
    "wildlife conservation scam",
    "environmental scam",
    "charity fraud",
    "non-profit scam",
    "religious scam",
    "spiritual scam",
    "self-help scam",
    "personal development scam",
    "motivational scam",
    "life coach scam",
    "business opportunity scam",
    "franchise scam",
    "multi-level marketing scam",
    "network marketing scam",
    "pyramid scheme",
    "work-from-home scam",
    "online business scam",
    "internet marketing scam",
    "affiliate marketing scam",
    "digital marketing scam",
    "social media scam",
    "influencer scam",
    "content creator scam",
    "blogging scam",
    "vlogging scam",
    "podcasting scam",
    "e-commerce scam",
    "dropshipping scam",
    "retail arbitrage scam",
    "wholesale scam",
    "import/export scam",
    "shipping scam",
    "logistics scam",
    "supply chain scam",
    "xxx",
    "adult scam",
    "porn scam",
    "dating scam",
    "escort scam",
    "massage parlor scam",
    "human trafficking",
]

